#criando database sprint_2 e tabelas CURSO, TURMA, ALUNO, FACILITADOR e ENTREGAS

create database sprint_2;
use sprint_2;

CREATE TABLE CURSO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
FRENTE VARCHAR(255)
);

CREATE TABLE TURMA (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CURSO INT,
    FOREIGN KEY (CURSO)
        REFERENCES CURSO (ID)
);
    
CREATE TABLE ALUNO (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255),
    CPF VARCHAR(11),
    ID_TURMA INT,
    FOREIGN KEY (ID_TURMA)
        REFERENCES TURMA (ID)
);

CREATE TABLE FACILITADOR (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255),
    FRENTE VARCHAR(255),
    ID_TURMA INT,
    FOREIGN KEY (ID_TURMA)
        REFERENCES TURMA (ID)
);

CREATE TABLE ENTREGAS (
    ID_ENTREGA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    link VARCHAR(500),
    modulo_projeto INT NOT NULL,
    id_aluno INT,
    FOREIGN KEY (id_aluno)
        REFERENCES aluno (ID),
        ID_TURMA INT,
    FOREIGN KEY (ID_TURMA)
        REFERENCES TURMA (ID),
    conceito VARCHAR(255)
);

# ADICIONANDO ATRIBUTO EMAIL COM TYPE TEXT

ALTER TABLE aluno ADD email text;
